### ISSUE TITLE
Question on rendering special effects with Markdown files

### ISSUE THREAD

**Issue by riven314** [ritchieng/deep-learning-wizard#12]
Thanks for making such a great collection of tutorials open source, Ritchie!

I am not raising a bug but instead have a genuine question on how you managed to render appealing effects like the following with your Markdown files. 
I tried pasting the same Markdown code, but didnt get the effect. Curious to know the magic that you did to make it happens!

![](https://i.ibb.co/5sgqfCb/Screenshot-2022-02-06-at-6-00-25-PM.png)
![](https://i.ibb.co/LzySs1t/Screenshot-2022-02-06-at-6-01-36-PM.png)

**Comment by ritchieng** [comment]
More than 1 year later I'm replying to this! Apologies.

If you look at the markdown, you will see that I use `:hourglass_flowing_sand:`.

It's part of material mkdocs theme, which you would have to install. 

File: https://github.com/ritchieng/deep-learning-wizard/blob/master/docs/deep_learning/course_progression.md
